# -- Project information -----------------------------------------------------

project = "Test build"
copyright = "2018, Executable Books Project"
author = "Executable Books Project"

extensions = ["sphinx_comments", "myst_parser"]

comments_config = {
    "hypothesis": True,
    "utterances": {"repo": "executablebooks/sphinx-comments", "theme": "footheme",},
    "dokieli": True,
}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"
